# Generated by Django 5.0.2 on 2024-02-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='ad_box',
            field=models.TextField(blank=True, null=True),
        ),
    ]
